package system;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrew
 */
public class BookingForm extends javax.swing.JFrame {

    dbManager newManager = new dbManager();
    internalClock clock = new internalClock();

    public BookingForm() {
        initComponents();
        populateReservationTable();
        setCurrentDate();
        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public final void populateReservationTable() {
        String columnNames[] = {"Employee", "Date", "Time", "Customer", "Table No."};
        DefaultTableModel tableModel = new DefaultTableModel(newManager.getReservationData(), columnNames);
        tableReservation.setModel(tableModel);
        tableReservation.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableReservation.getColumnModel().getColumn(1).setPreferredWidth(100);
        tableReservation.getColumnModel().getColumn(2).setPreferredWidth(75);
        tableReservation.getColumnModel().getColumn(3).setPreferredWidth(175);
        tableReservation.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    public String getCustomerName() {
        return textCustomerName.getText();
    }

    public String getEmployee() {
        return textEmp.getText();
    }

    public String getDate() {
        String date = comboboxYear.getSelectedItem().toString() + "-"
                + comboboxMonth.getSelectedItem().toString() + "-"
                + comboboxDay.getSelectedItem().toString();
        return date;
    }

    public int getTableNum() {
        return Integer.parseInt(textTable.getText());
    }

    public int getCustomerNum() {
        return Integer.parseInt(textCustomerNum.getText());
    }

    public String getTime() {
        String time = comboboxHour.getSelectedItem().toString()
                + ":" + comboboxMinute.getSelectedItem().toString();
        return time;
    }

    public final void setCurrentDate() {
        String currentDate = clock.getCurrentDate();
        String date[] = currentDate.split("-");
        String day = date[2];
        String month = date[1];
        comboboxDay.setSelectedItem(day);
        comboboxMonth.setSelectedItem(month);
    }

    public void checkMonth() {
        if (comboboxMonth.getSelectedItem() == "02") {
            comboboxDay.removeItem("31");
            comboboxDay.removeItem("30");
            comboboxDay.removeItem("29");
        }
        if (comboboxMonth.getSelectedItem() == "01" || comboboxMonth.getSelectedItem() == "03"
                || comboboxMonth.getSelectedItem() == "05" || comboboxMonth.getSelectedItem() == "07"
                || comboboxMonth.getSelectedItem() == "08" || comboboxMonth.getSelectedItem() == "10"
                || comboboxMonth.getSelectedItem() == "12") {
            comboboxDay.removeItem("31");
            comboboxDay.removeItem("30");
            comboboxDay.removeItem("29");
            comboboxDay.addItem("29");
            comboboxDay.addItem("30");
            comboboxDay.addItem("31");
            if (comboboxDay.getSelectedItem() == "28" || comboboxDay.getSelectedItem() == "30") {
                comboboxDay.setSelectedItem("31");
            }
        }
        if (comboboxMonth.getSelectedItem() == "04" || comboboxMonth.getSelectedItem() == "06"
                || comboboxMonth.getSelectedItem() == "09" || comboboxMonth.getSelectedItem() == "11") {
            comboboxDay.removeItem("31");
            comboboxDay.removeItem("30");
            comboboxDay.removeItem("29");
            comboboxDay.addItem("29");
            comboboxDay.addItem("30");
            if (comboboxDay.getSelectedItem() == "28" || comboboxDay.getSelectedItem() == "31") {
                comboboxDay.setSelectedItem("30");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        buttonAccept1 = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        comboboxHour = new javax.swing.JComboBox<>();
        comboboxMinute = new javax.swing.JComboBox<>();
        lblNumber2 = new javax.swing.JLabel();
        lblNumber1 = new javax.swing.JLabel();
        textCustomerNum = new javax.swing.JTextField();
        textEmp = new javax.swing.JTextField();
        lblNumber = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblNumber3 = new javax.swing.JLabel();
        textTable = new javax.swing.JTextField();
        buttonCancel = new javax.swing.JButton();
        lblNumber4 = new javax.swing.JLabel();
        textCustomerName = new javax.swing.JTextField();
        comboboxMonth = new javax.swing.JComboBox<>();
        comboboxDay = new javax.swing.JComboBox<>();
        comboboxYear = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservation = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        buttonAccept1.setBackground(new java.awt.Color(75, 75, 75));
        buttonAccept1.setForeground(new java.awt.Color(255, 255, 255));
        buttonAccept1.setText("Accept");
        buttonAccept1.setContentAreaFilled(false);
        buttonAccept1.setOpaque(true);
        buttonAccept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccept1ActionPerformed(evt);
            }
        });

        lblTime.setText("Time ");

        comboboxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        comboboxMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45", " " }));

        lblNumber2.setText("Date");

        lblNumber1.setText("No. of customers");

        textCustomerNum.setBackground(new java.awt.Color(240, 240, 240));
        textCustomerNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCustomerNumActionPerformed(evt);
            }
        });

        textEmp.setBackground(new java.awt.Color(240, 240, 240));
        textEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmpActionPerformed(evt);
            }
        });

        lblNumber.setText("Employee ID");

        lblTitle.setText("Bookings");

        lblNumber3.setText("Table No.");

        textTable.setBackground(new java.awt.Color(240, 240, 240));
        textTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTableActionPerformed(evt);
            }
        });

        buttonCancel.setBackground(new java.awt.Color(75, 75, 75));
        buttonCancel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancel.setText("Close");
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setOpaque(true);
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        lblNumber4.setText("Customer Name");

        textCustomerName.setBackground(new java.awt.Color(240, 240, 240));
        textCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCustomerNameActionPerformed(evt);
            }
        });

        comboboxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        comboboxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboboxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumber1)
                                    .addComponent(lblTime)
                                    .addComponent(lblNumber2))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textCustomerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(comboboxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboboxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(comboboxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboboxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboboxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblNumber4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumber)
                                    .addComponent(lblNumber3))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textTable)
                                    .addComponent(textEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAccept1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumber)
                    .addComponent(textEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber3)
                    .addComponent(textTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber4)
                    .addComponent(textCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCustomerNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumber2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTime))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAccept1)
                    .addComponent(buttonCancel))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Add Revervation", jPanel1);

        jScrollPane1.setBorder(null);

        tableReservation.setAutoCreateRowSorter(true);
        tableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee ID", "Date", "Table No.", "No.of People"
            }
        ));
        tableReservation.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tableReservation);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmpActionPerformed
//        Checkout s = new Checkout();
//        s.setLocation(350, 530);
//        s.setVisible(true);
    }//GEN-LAST:event_textEmpActionPerformed

    private void buttonAccept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccept1ActionPerformed
        newManager.insertReservations(getEmployee(), getDate(), getTime(), getCustomerName(), getTableNum(), getCustomerNum());
        populateReservationTable();
    }//GEN-LAST:event_buttonAccept1ActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textCustomerNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCustomerNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCustomerNumActionPerformed

    private void textCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCustomerNameActionPerformed

    private void textTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccept1;
    private javax.swing.JButton buttonCancel;
    public static javax.swing.JComboBox<String> comboboxDay;
    public static javax.swing.JComboBox<String> comboboxHour;
    public static javax.swing.JComboBox<String> comboboxMinute;
    public static javax.swing.JComboBox<String> comboboxMonth;
    public static javax.swing.JComboBox<String> comboboxYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblNumber1;
    private javax.swing.JLabel lblNumber2;
    private javax.swing.JLabel lblNumber3;
    private javax.swing.JLabel lblNumber4;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    public static javax.swing.JTable tableReservation;
    public static javax.swing.JTextField textCustomerName;
    public static javax.swing.JTextField textCustomerNum;
    public static javax.swing.JTextField textEmp;
    public static javax.swing.JTextField textTable;
    // End of variables declaration//GEN-END:variables
}
